# Generated by Django 5.0.7 on 2024-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_description_city_icon_city_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
